"""empty message

Revision ID: 0e74dde840f8
Revises: 8a34ee455d6d
Create Date: 2025-11-19 13:08:06.290944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e74dde840f8'
down_revision = '8a34ee455d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memory_used', sa.Integer(), nullable=True))
        batch_op.drop_column('memory_cost')
        batch_op.drop_column('time_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_cost', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('memory_cost', sa.INTEGER(), nullable=True))
        batch_op.drop_column('memory_used')
        batch_op.drop_column('time_used')

    # ### end Alembic commands ###
