"""Add OCR fields

Revision ID: 39c9b4516d4c
Revises: b9e047da44f4
Create Date: 2025-12-15 23:49:52.970803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c9b4516d4c'
down_revision = 'b9e047da44f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_api_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ocr_api_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ocr_model', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ocr_model')
        batch_op.drop_column('ocr_api_url')
        batch_op.drop_column('ocr_api_key')

    # ### end Alembic commands ###
